{\rtf1\ansi\deff0\deftab720{\fonttbl{\f0\fmodern Courier New;}}
{\colortbl\red51\green153\blue255;\red0\green128\blue0;\red0\green0\blue0;\red255\green255\blue255;\red255\green255\blue255;\red128\green0\blue128;\red255\green0\blue0;}
{\info{\comment Generated by the SynEdit RTF exporter}
{\title Untitled}}

\deflang1033\pard\plain\f0\fs20 \cf0\i /* 
\par Taylor Kopel
\par Written assignment 1
\par Part B question 1
\par */
\par 
\par \i0\cf1 #include <stdio.h>
\par \cf2\b int\b0\cb3  \cb4 main()
\par \{
\par \cb3 	\cb4\b int\b0\cb3  \cb4 save1;\cb3  \cb4\cf0\i /*creating a variable named save2 that will store an integer*/
\par \i0\cb3\cf2 	\cb4\b int\b0\cb3  \cb4 save2;\cb3  \cb4\cf0\i /*creating a variable named save2 that will store an integer*/
\par \i0\cb3\cf2 	\cb4\b int\b0\cb3  \cb4 total;\cb3  \cb4\cf0\i /*creating a variable named total that will store the sum of save1 and save2*/
\par \i0\cb3\cf2 	\cb4\b int\b0\cb3  \cb4 average;\cb3  \cb4\cf0\i /*creating a variable named average that will store the average of the sum of save1 and save2*/
\par 
\par \i0\cb3\cf2 	\cb4 save1\cb3  \cb4 =\cb3  \cb4\cf5 5\cf2 ;\cb3  \cb4\cf0\i /*inputs 5 for the value of save1*/
\par \i0\cb3\cf2 	\cb4 save2\cb3  \cb4 =\cb3  \cb4\cf5 2\cf2 ;\cb3  \cb4\cf0\i /*inputs 2 for the value of save2*/
\par \i0\cb3\cf2 	\cb4 total\cb3  \cb4 =\cb3  \cb4 save1\cb3  \cb4 +\cb3  \cb4 save2;\cb3  \cb4\cf0\i /*tells the computer to add save1 and save2 together and input the value into total*/
\par \i0\cb3\cf2 	\cb4 average\cb3  \cb4 =\cb3  \cb4 total\cb3  \cb4 /\cb3  \cb4\cf5 2.0\cf2 ;\cb3  \cb4\cf0\i /*tells the computer to divide the value known as total by 2 and input the value into average*/
\par \i0\cb3\cf2 	\cb4 printf(\cf6 "The total sum of save1 and save2 is %d\\n"\cf2 ,\cb3  \cb4 total);\cb3  \cb4\cf0\i /*this will display the number stored as total*/
\par \i0\cb3\cf2 	\cb4 printf(\cf6 "The average of save1 and save2 is %d\\n"\cf2 ,\cb3  \cb4 average);\cb3  \cb4\cf0\i /*this will display the number stored as average*/
\par \i0\cb3\cf2 	\cb4 printf(\cf6 "Press enter to continue \\n"\cf2 );\cb3  \cb4\cf0\i /* this is just an informative prompt*/\i0\cb3\cf2 	
\par 	
\par 	\cb4 getchar();\cb3  
\par 	\cb4\b return\b0\cb3  \cb4\cf5 0\cf2 ;
\par \}
\par }